package com.webapp.fdbkrestful.utility;

public enum Designation {
    CHAIRPERSON, VICECHAIRPERSON, SECRETARY, DIRECTOR, REGISTRAR, HOD, HODANDPROFESSOR, PROFESSOR, ASSOCIATEPROFESSOR, ASSISTANTPROFESSOR,
    LIBRARIAN, RECTOR, MESSOWNER, PHYSICALDIRECTOR, LABORATORYASSISTANT, CLERK, PEON, SWEEPER
}
